import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { translator } from '@tests/support/intl';
import { SHOT_META, shotPath } from '@/utils/guides/shots';

describe('guide screenshots', () => {
  /**
   * The namespace is what lets a non-game screenshot exist at all - before
   * it, every shot resolved under `games/` whatever it was of.
   */
  it('resolves a shot under its own namespace, not a hardcoded one', () => {
    expect(shotPath('relay/access-tabs')).toBe('/og/guides/relay/access-tabs.png');
    expect(shotPath('games/vesta-board')).toBe('/og/guides/games/vesta-board.png');
  });

  /**
   * The alt text is the only description of these images that reaches a
   * screen reader or a search engine, and the files are generated by a script
   * nobody runs on every build - so both are worth asserting.
   */
  it('every declared shot has a file on disk and non-trivial alt text', () => {
    for (const [name, meta] of Object.entries(SHOT_META)) {
      const file = join(process.cwd(), 'public', shotPath(name));
      const how = name.startsWith('games/')
        ? 'run npm run snap-games'
        : 'it is a capture committed by hand - see the note in src/utils/guides/shots.ts';
      expect(existsSync(file), `${name}.png is missing - ${how}`).toBe(true);
      expect(readFileSync(file).length).toBeGreaterThan(1000);
      for (const locale of ['en', 'es', 'pt'] as const) {
        expect(translator(locale)(meta.altKey).length, `${locale} ${name}`).toBeGreaterThan(40);
      }
      expect(meta.width).toBeGreaterThan(0);
      expect(meta.height).toBeGreaterThan(0);
    }
  });
});
