import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

// The page resolves the request locale on the server now, so the headers
// and cookies it reads have to exist. English keeps the expectations below
// readable as copy rather than as key names.
vi.mock('next/headers', () => ({
  headers: async () => new Map([['x-obelisk-locale', 'en']]) as unknown as Headers,
  cookies: async () => ({ get: () => undefined }),
}));

import FeaturesPage from './page';

vi.mock('@/components/Navbar', () => ({ default: () => <nav>Obelisk</nav> }));
vi.mock('@/components/Footer', () => ({ default: () => <footer /> }));
vi.mock('@/components/ShootingStars', () => ({ default: () => null }));

describe('FeaturesPage', () => {
  it('shows every comeback feature with a screenshot and working calls to action', async () => {
    render(await FeaturesPage());
    for (const title of ['Nostr relay-based groups', 'Voice messages', 'Sticker marketplace', 'Games in the channel', 'Mobile PWA', 'Peer-to-peer video calls', 'Big calls with SFU', 'Nostr profile explorer']) {
      expect(screen.getByRole('heading', { name: title })).toBeInTheDocument();
    }
    expect(screen.getAllByRole('img')).toHaveLength(8);
    expect(screen.getByRole('img', { name: 'Obelisk desktop sticker, emoji, and GIF marketplace' })).toHaveAttribute('src', expect.stringContaining('stickers-marketplace.png'));
    expect(screen.getAllByRole('img').filter((image) => image.getAttribute('src')?.includes('voice-messages.png'))).toHaveLength(2);
    expect(screen.getAllByRole('img').filter((image) => image.getAttribute('src')?.includes('desktop-large-voice-channel-with-sfu-peer-trasmission-test.png'))).toHaveLength(2);
    expect(screen.getByText(/Choose which SFU server to use or host your own/)).toBeInTheDocument();
    // The games shot is generated by `npm run snap-games`, not hand-placed.
    expect(screen.getByRole('img', { name: /Chain Reaction board, a Vesta island, and a Stacker well/ }))
      .toHaveAttribute('src', expect.stringContaining('games-feature.png'));
    expect(screen.getAllByRole('link', { name: /open obelisk|launch the app/i })).toHaveLength(2);
    expect(screen.getByRole('link', { name: 'View source' })).toHaveAttribute('href', 'https://github.com/obelisk-app/obelisk');
  });
});
