import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import Clip, { CLIP_META, clipPath, clipPosterPath } from './Clip';

/**
 * jsdom has no `matchMedia`, so every test declares what the reader has asked
 * their OS for. The default is "no preference" — the autoplay path.
 */
function setReducedMotion(reduced: boolean) {
  vi.stubGlobal(
    'matchMedia',
    vi.fn((query: string) => ({
      matches: reduced && query.includes('prefers-reduced-motion'),
      media: query,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      addListener: vi.fn(),
      removeListener: vi.fn(),
      dispatchEvent: vi.fn(),
      onchange: null,
    })),
  );
}

describe('Clip', () => {
  beforeEach(() => setReducedMotion(false));

  it('renders the clip with its poster, label and intrinsic size', () => {
    render(<Clip name="relay/install" />);
    const video = screen.getByLabelText(CLIP_META['relay/install'].alt);
    expect(video.getAttribute('src')).toBe('/media-kit/video/relay/install.mp4');
    expect(video.getAttribute('poster')).toBe('/og/guides/relay/clip-install.jpg');
    expect(video.getAttribute('width')).toBe('640');
    expect(video.getAttribute('height')).toBe('360');
  });

  it('renders a caption with the runtime, so the reader knows it is short and silent', () => {
    render(<Clip name="relay/ladder" caption="Three tiers and a block list" />);
    expect(screen.getByText('Three tiers and a block list')).toBeTruthy();
    expect(screen.getByText('32s, no sound')).toBeTruthy();
  });

  it('renders nothing for an unknown clip rather than a broken player', () => {
    const { container } = render(<Clip name="not-a-clip" />);
    expect(container.firstChild).toBeNull();
  });

  it('loops silently with no controls by default', () => {
    render(<Clip name="relay/numbers" />);
    const video = screen.getByLabelText(CLIP_META['relay/numbers'].alt) as HTMLVideoElement;
    expect(video.hasAttribute('controls')).toBe(false);
    expect(video.hasAttribute('loop')).toBe(true);
    expect(video.hasAttribute('autoplay')).toBe(true);
    expect(video.muted || video.hasAttribute('muted')).toBe(true);
  });

  /**
   * A 32-second loop is exactly what this query is asked to stop. Degrading
   * to the poster plus a play button keeps the picture and drops the motion.
   */
  it('does not autoplay or loop when the reader prefers reduced motion', () => {
    setReducedMotion(true);
    render(<Clip name="relay/snapshot" />);
    const video = screen.getByLabelText(CLIP_META['relay/snapshot'].alt);
    expect(video.hasAttribute('autoplay')).toBe(false);
    expect(video.hasAttribute('loop')).toBe(false);
    expect(video.hasAttribute('controls')).toBe(true);
    expect(video.getAttribute('poster')).toBe('/og/guides/relay/clip-snapshot.jpg');
  });

  /**
   * These files are committed by hand from the media repo, not generated by
   * anything in this one, so nothing else would notice them going missing.
   */
  it('every declared clip has a video and a poster on disk, with real alt text', () => {
    for (const [name, meta] of Object.entries(CLIP_META)) {
      const video = join(process.cwd(), 'public', clipPath(name));
      const poster = join(process.cwd(), 'public', clipPosterPath(name));
      expect(existsSync(video), `${clipPath(name)} is missing`).toBe(true);
      expect(existsSync(poster), `${clipPosterPath(name)} is missing`).toBe(true);
      expect(readFileSync(video).length).toBeGreaterThan(10_000);
      expect(readFileSync(poster).length).toBeGreaterThan(1000);
      expect(meta.alt.length).toBeGreaterThan(40);
      expect(meta.seconds).toBeGreaterThan(0);
      expect(meta.width).toBeGreaterThan(0);
      expect(meta.height).toBeGreaterThan(0);
    }
  });
});
