/**
 * A screenshot of the running app, for guides that describe the app itself.
 *
 * The heroes and diagrams next door are drawings — nice, but a drawing of a
 * game board is a claim, not evidence. These images come out of
 * `npm run snap-games`, which photographs the real components rendering a
 * board they derived from a real event log (see `src/app/dev/game-shots/`).
 * Re-running the script after a rules change updates every guide at once.
 *
 * Sizes are the intrinsic CSS size: the PNGs are captured at 2x, so `width`
 * here is half the pixel width. Setting both keeps the layout from jumping
 * while the image loads.
 *
 * Names are namespaced by where the picture comes from — `games/…` for the
 * snapped components above, `relay/…` for captures of Obelisk Relay's admin
 * console, which is a different program and cannot be photographed from
 * here. The namespace is the directory under `public/og/guides/`.
 */
export interface ShotMeta {
  alt: string;
  width: number;
  height: number;
}

export const SHOT_META: Record<string, ShotMeta> = {
  'games/chain-reaction-board': {
    width: 420,
    height: 484,
    alt: 'Chain Reaction board in Obelisk: a 6×9 grid of dark cells holding glowing red, lime and cyan orbs, with a legend naming the three players and whose turn it is.',
  },
  'games/chain-reaction-result': {
    width: 380,
    height: 181,
    alt: 'Chain Reaction final standings in Obelisk: first place with a trophy and an orb count, second place marked out, under the heading "Final result".',
  },
  'games/vesta-board': {
    width: 860,
    height: 870,
    alt: 'Vesta board in Obelisk: a hexagonal island of resource tiles with numbered dice tokens, player settlements and roads on the edges, a robber on the desert, and each player’s hand and victory points below.',
  },
  'games/stacker-well': {
    width: 340,
    height: 475,
    alt: 'A Stacker playfield in Obelisk: a ten-column well part-filled with coloured tetromino blocks and the ghost outline of the falling piece near the top.',
  },
  'games/stacker-table': {
    width: 760,
    height: 874,
    alt: 'A live three-player Stacker match in Obelisk: the player’s own well with grey garbage lines at the bottom, hold and next-piece rails, and two opponents shown as miniature boards with their attack and line counts.',
  },
  'games/game-picker': {
    width: 448,
    height: 444,
    alt: 'The Obelisk "Pick a game" dialog listing Chain Reaction, Vesta and Stacker, each with a thumbnail, a one-line description, its player range and its turn clock.',
  },

  /*
   * Obelisk Relay's admin console. Unlike the `games/` set these are not
   * generated by a script in this repo — the relay is a different program,
   * so they are captures of a live deployment (public.obelisk.ar, tag
   * v2026.09.22-conncount2-arm64) downscaled from the 2880×1800 originals
   * in obelisk-relay/screenshots/v2. They are purple because that is the
   * relay's accent; this app's lime is the client.
   */
  'relay/landing': {
    width: 700,
    height: 300,
    alt: 'The connect card on an Obelisk Relay landing page: counters reading 28 groups and 9 supported NIPs, above the relay address wss://public.obelisk.ar with a copy button.',
  },
  'relay/sign-in': {
    width: 450,
    height: 530,
    alt: 'The Obelisk Relay admin sign-in card offering three Nostr identities: a NIP-07 browser extension, a NIP-46 remote signer, or a pasted private key marked risky in browsers.',
  },
  'relay/overview': {
    width: 800,
    height: 500,
    alt: 'The Overview screen of the Obelisk Relay console: hourly graphs of active connections and disk used, live counters for connections, uptime and last event received, and a configured summary showing retention, database size and the access mode.',
  },
  'relay/access-tabs': {
    width: 800,
    height: 500,
    alt: 'The Access screen of the Obelisk Relay console: a box for checking whether an account is allowed, five tabs counting Tier 1, Tier 2, Tier 3, Blocked and Policies, and the reference accounts every tier is measured from.',
  },
  'relay/budget-ladder': {
    width: 800,
    height: 500,
    alt: 'The rate budget in the Obelisk Relay console: bars showing what each tier may publish — 6,000 events a minute for Tier 1, 3,000 for Tier 2, 1,500 for Tier 3 and 600 for no tier at all.',
  },
  'relay/key-search': {
    width: 800,
    height: 500,
    alt: 'Checking one account in the Obelisk Relay console: a pasted npub answered with "Allowed", admitted by web of trust at two hops from a reference account, with a Block button beside the verdict.',
  },
  'relay/reports': {
    width: 800,
    height: 500,
    alt: 'The Reports screen of the Obelisk Relay console: moderation reports grouped one row per reported thing, each tagged nudity or spam with its reporter count, a note field, and buttons to dismiss or block the reported account.',
  },
  'relay/storage': {
    width: 800,
    height: 500,
    alt: 'The Storage screen of the Obelisk Relay console: 227.1 MB on disk holding 12,831 events, nothing deleted, with a warning that pruning stops the database file growing but does not shrink it.',
  },
};

export function shotPath(name: string): string {
  return `/og/guides/${name}.png`;
}

export default function Shot({
  name,
  caption,
  /** Cap the rendered width; the natural size is often wider than the column. */
  maxWidth,
}: {
  name: string;
  caption?: string;
  maxWidth?: number;
}) {
  const meta = SHOT_META[name];
  if (!meta) return null;
  return (
    <figure className="my-8 w-full" data-testid={`shot-${name}`}>
      <div className="w-full overflow-hidden rounded-xl border border-lc-border bg-lc-dark">
        {/* Plain <img>: these are already the exact pixels we want, and
            next/image would re-encode a screenshot of a dark UI badly. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={shotPath(name)}
          alt={meta.alt}
          width={meta.width}
          height={meta.height}
          className="mx-auto block h-auto w-full"
          style={maxWidth ? { maxWidth } : undefined}
          loading="lazy"
          decoding="async"
        />
      </div>
      {caption && (
        <figcaption className="mt-2 text-center text-sm text-lc-muted">{caption}</figcaption>
      )}
    </figure>
  );
}
