import { useTranslations } from 'next-intl';
import type { MessageKey } from '@/i18n/keys';

/**
 * A screenshot of the running app, for guides that describe the app itself.
 *
 * The heroes and diagrams next door are drawings - nice, but a drawing of a
 * game board is a claim, not evidence. These images come out of
 * `npm run snap-games`, which photographs the real components rendering a
 * board they derived from a real event log (see `src/app/dev/game-shots/`).
 * Re-running the script after a rules change updates every guide at once.
 *
 * Sizes are the intrinsic CSS size: the PNGs are captured at 2x, so `width`
 * here is half the pixel width. Setting both keeps the layout from jumping
 * while the image loads.
 *
 * Names are namespaced by where the picture comes from - `games/…` for the
 * snapped components above, `relay/…` for captures of Obelisk Relay's admin
 * console, which is a different program and cannot be photographed from
 * here. The namespace is the directory under `public/og/guides/`.
 */
export interface ShotMeta {
  /** The image's alt text: `guides.shot.alt.*`. */
  altKey: MessageKey;
  width: number;
  height: number;
}

export const SHOT_META: Record<string, ShotMeta> = {
  'games/chain-reaction-board': {
    width: 420,
    height: 484,
    altKey: 'guides.shot.alt.chainReactionBoard',
  },
  'games/chain-reaction-result': {
    width: 380,
    height: 181,
    altKey: 'guides.shot.alt.chainReactionResult',
  },
  'games/vesta-board': {
    width: 860,
    height: 870,
    altKey: 'guides.shot.alt.vestaBoard',
  },
  'games/stacker-well': {
    width: 340,
    height: 475,
    altKey: 'guides.shot.alt.stackerWell',
  },
  'games/stacker-table': {
    width: 760,
    height: 874,
    altKey: 'guides.shot.alt.stackerTable',
  },
  'games/game-picker': {
    width: 448,
    height: 444,
    altKey: 'guides.shot.alt.gamePicker',
  },

  /*
   * Obelisk Relay's admin console. Unlike the `games/` set these are not
   * generated by a script in this repo - the relay is a different program,
   * so they are captures of a live deployment (public.obelisk.ar, tag
   * v2026.09.22-conncount2-arm64) downscaled from the 2880×1800 originals
   * in obelisk-relay/screenshots/v2. They are purple because that is the
   * relay's accent; this app's lime is the client.
   */
  'relay/landing': {
    width: 700,
    height: 300,
    altKey: 'guides.shot.alt.relayLanding',
  },
  'relay/sign-in': {
    width: 450,
    height: 530,
    altKey: 'guides.shot.alt.relaySignIn',
  },
  'relay/overview': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayOverview',
  },
  'relay/access-tabs': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayAccessTabs',
  },
  'relay/budget-ladder': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayBudgetLadder',
  },
  'relay/key-search': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayKeySearch',
  },
  'relay/reports': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayReports',
  },
  'relay/storage': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayStorage',
  },
};

export function shotPath(name: string): string {
  return `/og/guides/${name}.png`;
}

export default function Shot({
  name,
  caption,
  /** Cap the rendered width; the natural size is often wider than the column. */
  maxWidth,
}: {
  name: string;
  caption?: string;
  maxWidth?: number;
}) {
  const t = useTranslations();
  const meta = SHOT_META[name];
  if (!meta) return null;
  return (
    <figure className="my-8 w-full" data-testid={`shot-${name}`}>
      <div className="w-full overflow-hidden rounded-xl border border-lc-border bg-lc-dark">
        {/* Plain <img>: these are already the exact pixels we want, and
            next/image would re-encode a screenshot of a dark UI badly. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={shotPath(name)}
          alt={t(meta.altKey)}
          width={meta.width}
          height={meta.height}
          className="mx-auto block h-auto w-full"
          style={maxWidth ? { maxWidth } : undefined}
          loading="lazy"
          decoding="async"
        />
      </div>
      {caption && (
        <figcaption className="mt-2 text-center text-sm text-lc-muted">{caption}</figcaption>
      )}
    </figure>
  );
}
