import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import Shot, { SHOT_META, shotPath } from './Shot';

describe('Shot', () => {
  it('renders the screenshot with its alt text and intrinsic size', () => {
    render(<Shot name="chain-reaction-board" />);
    const img = screen.getByAltText(SHOT_META['chain-reaction-board'].alt);
    expect(img.getAttribute('src')).toBe('/og/guides/games/chain-reaction-board.png');
    expect(img.getAttribute('width')).toBe('420');
    expect(img.getAttribute('height')).toBe('484');
  });

  it('renders a caption when given one', () => {
    render(<Shot name="stacker-well" caption="A well mid-match" />);
    expect(screen.getByText('A well mid-match')).toBeTruthy();
  });

  it('renders nothing for an unknown shot rather than a broken image', () => {
    const { container } = render(<Shot name="not-a-shot" />);
    expect(container.firstChild).toBeNull();
  });

  /**
   * The alt text is the only description of these images that reaches a
   * screen reader or a search engine, and the files are generated by a script
   * nobody runs on every build — so both are worth asserting.
   */
  it('every declared shot has a file on disk and non-trivial alt text', () => {
    for (const [name, meta] of Object.entries(SHOT_META)) {
      const file = join(process.cwd(), 'public', shotPath(name));
      expect(existsSync(file), `${name}.png is missing — run npm run snap-games`).toBe(true);
      expect(readFileSync(file).length).toBeGreaterThan(1000);
      expect(meta.alt.length).toBeGreaterThan(40);
      expect(meta.width).toBeGreaterThan(0);
      expect(meta.height).toBeGreaterThan(0);
    }
  });
});
