import type { EmojiEntry } from '../types';

/** The Nature tab of the picker. */
export const NATURE: EmojiEntry[] = [
    { char: '🌹', keywords: ['rose', 'flower', 'rosa', 'flor'] },
    { char: '🌺', keywords: ['hibiscus', 'flower', 'flor'] },
    { char: '🌸', keywords: ['cherryblossom', 'flower', 'sakura', 'flor', 'cerezo'] },
    { char: '🌼', keywords: ['blossom', 'flower', 'margarita', 'flor'] },
    { char: '🌻', keywords: ['sunflower', 'flower', 'girasol', 'flor'] },
    { char: '🌷', keywords: ['tulip', 'flower', 'tulipan', 'flor'] },
    { char: '💐', keywords: ['bouquet', 'ramo', 'flores'] },
    { char: '🍀', keywords: ['fourleaf', 'clover', 'luck', 'trebol', 'suerte'] },
    { char: '🍁', keywords: ['mapleleaf', 'leaf', 'arce', 'hoja', 'otono'] },
    { char: '🍂', keywords: ['fallen', 'leaves', 'hojas', 'caidas', 'otono'] },
    { char: '🍃', keywords: ['leaf', 'wind', 'hoja', 'viento'] },
    { char: '🌿', keywords: ['herb', 'leaf', 'hierba', 'planta', 'hoja'] },
    { char: '🌱', keywords: ['seedling', 'plant', 'planta', 'brote'] },
    { char: '🌳', keywords: ['tree', 'arbol'] },
    { char: '🌲', keywords: ['evergreen', 'pine', 'tree', 'pino', 'arbol'] },
    { char: '🌴', keywords: ['palm', 'tree', 'palmera'] },
    { char: '🌵', keywords: ['cactus'] },
    { char: '🌾', keywords: ['wheat', 'rice', 'trigo', 'arroz'] },
    { char: '🪴', keywords: ['pottedplant', 'plant', 'maceta', 'planta'] },
    { char: '🌍', keywords: ['earth', 'globe', 'tierra', 'mundo', 'planeta'] },
    { char: '🌎', keywords: ['earth', 'americas', 'tierra', 'america'] },
    { char: '🌏', keywords: ['earth', 'asia', 'tierra'] },
    { char: '🌑', keywords: ['newmoon', 'moon', 'luna', 'nueva'] },
    { char: '🌕', keywords: ['fullmoon', 'moon', 'luna', 'llena'] },
    { char: '🌝', keywords: ['fullmoonface', 'moon', 'luna', 'cara'] },
    { char: '🌚', keywords: ['newmoonface', 'moon', 'luna', 'cara'] },
    { char: '⛅', keywords: ['cloudysun', 'partly', 'cloudy', 'nublado', 'sol'] },
    { char: '🌧️', keywords: ['rain', 'cloud', 'lluvia', 'nube'] },
    { char: '⛈️', keywords: ['thunderstorm', 'storm', 'tormenta', 'rayo'] },
    { char: '🌨️', keywords: ['snow', 'cloud', 'nieve', 'nube'] },
    { char: '❄️', keywords: ['snowflake', 'snow', 'cold', 'copo', 'nieve', 'frio'] },
    { char: '☃️', keywords: ['snowman', 'mas', 'munieco', 'nieve'] },
    { char: '🌊', keywords: ['wave', 'water', 'ocean', 'ola', 'agua', 'mar'] },
    { char: '🌪️', keywords: ['tornado', 'twister'] },
    { char: '🌫️', keywords: ['fog', 'niebla'] },
];
