/**
 * Guides: shots. Values the code in `utils/guides/shots.ts` reads, kept here
 * so every reader imports the one copy.
 */

import type { ShotMeta } from '@/utils/guides/shots';

export const SHOT_META: Record<string, ShotMeta> = {
  'games/chain-reaction-board': {
    width: 420,
    height: 484,
    altKey: 'guides.shot.alt.chainReactionBoard',
  },
  'games/chain-reaction-result': {
    width: 380,
    height: 181,
    altKey: 'guides.shot.alt.chainReactionResult',
  },
  'games/vesta-board': {
    width: 860,
    height: 870,
    altKey: 'guides.shot.alt.vestaBoard',
  },
  'games/stacker-well': {
    width: 340,
    height: 475,
    altKey: 'guides.shot.alt.stackerWell',
  },
  'games/stacker-table': {
    width: 760,
    height: 874,
    altKey: 'guides.shot.alt.stackerTable',
  },
  'games/game-picker': {
    width: 448,
    height: 444,
    altKey: 'guides.shot.alt.gamePicker',
  },

  /*
   * Obelisk Relay's admin console. Unlike the `games/` set these are not
   * generated by a script in this repo - the relay is a different program,
   * so they are captures of a live deployment (public.obelisk.ar, tag
   * v2026.09.22-conncount2-arm64) downscaled from the 2880×1800 originals
   * in obelisk-relay/screenshots/v2. They are purple because that is the
   * relay's accent; this app's lime is the client.
   */
  'relay/landing': {
    width: 700,
    height: 300,
    altKey: 'guides.shot.alt.relayLanding',
  },
  'relay/sign-in': {
    width: 450,
    height: 530,
    altKey: 'guides.shot.alt.relaySignIn',
  },
  'relay/overview': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayOverview',
  },
  'relay/access-tabs': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayAccessTabs',
  },
  'relay/budget-ladder': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayBudgetLadder',
  },
  'relay/key-search': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayKeySearch',
  },
  'relay/reports': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayReports',
  },
  'relay/storage': {
    width: 800,
    height: 500,
    altKey: 'guides.shot.alt.relayStorage',
  },
};
