import { describe, it, expect } from 'vitest';
import { render as rtlRender, screen } from '@testing-library/react';
import type { ReactElement } from 'react';
import { LocaleProvider, translator } from '@tests/support/intl';
import type { Locale } from '@/i18n';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import Shot, { SHOT_META, shotPath } from '@/components/guides/mdx/Shot';

const render = (ui: ReactElement, locale: Locale = 'en') =>
  rtlRender(<LocaleProvider initialLocale={locale}>{ui}</LocaleProvider>);

describe('Shot', () => {
  it('renders the screenshot with its alt text and intrinsic size', () => {
    render(<Shot name="games/chain-reaction-board" />);
    const img = screen.getByAltText(translator('en')(SHOT_META['games/chain-reaction-board'].altKey));
    expect(img.getAttribute('src')).toBe('/og/guides/games/chain-reaction-board.png');
    expect(img.getAttribute('width')).toBe('420');
    expect(img.getAttribute('height')).toBe('484');
  });

  it('describes the screenshot in the reader\'s language', () => {
    render(<Shot name="games/vesta-board" />, 'pt');
    expect(screen.getByAltText(translator('pt')(SHOT_META['games/vesta-board'].altKey))).toBeTruthy();
    expect(translator('pt')(SHOT_META['games/vesta-board'].altKey)).toMatch(/^Tabuleiro do Vesta/);
  });

  it('renders a caption when given one', () => {
    render(<Shot name="games/stacker-well" caption="A well mid-match" />);
    expect(screen.getByText('A well mid-match')).toBeTruthy();
  });

  it('renders nothing for an unknown shot rather than a broken image', () => {
    const { container } = render(<Shot name="not-a-shot" />);
    expect(container.firstChild).toBeNull();
  });

  /**
   * The namespace is what lets a non-game screenshot exist at all - before
   * it, every shot resolved under `games/` whatever it was of.
   */
  it('resolves a shot under its own namespace, not a hardcoded one', () => {
    expect(shotPath('relay/access-tabs')).toBe('/og/guides/relay/access-tabs.png');
    expect(shotPath('games/vesta-board')).toBe('/og/guides/games/vesta-board.png');
  });

  /**
   * The alt text is the only description of these images that reaches a
   * screen reader or a search engine, and the files are generated by a script
   * nobody runs on every build - so both are worth asserting.
   */
  it('every declared shot has a file on disk and non-trivial alt text', () => {
    for (const [name, meta] of Object.entries(SHOT_META)) {
      const file = join(process.cwd(), 'public', shotPath(name));
      const how = name.startsWith('games/')
        ? 'run npm run snap-games'
        : 'it is a capture committed by hand - see the note in Shot.tsx';
      expect(existsSync(file), `${name}.png is missing - ${how}`).toBe(true);
      expect(readFileSync(file).length).toBeGreaterThan(1000);
      for (const locale of ['en', 'es', 'pt'] as const) {
        expect(translator(locale)(meta.altKey).length, `${locale} ${name}`).toBeGreaterThan(40);
      }
      expect(meta.width).toBeGreaterThan(0);
      expect(meta.height).toBeGreaterThan(0);
    }
  });
});
