import type { EmojiEntry } from './types';

/** The Activities tab of the picker. */
export const ACTIVITIES: EmojiEntry[] = [
    { char: '⚽', keywords: ['soccer', 'football', 'futbol', 'pelota'] },
    { char: '🏀', keywords: ['basketball', 'basket', 'pelota'] },
    { char: '🏈', keywords: ['football', 'american', 'pelota'] },
    { char: '⚾', keywords: ['baseball', 'pelota'] },
    { char: '🎾', keywords: ['tennis', 'pelota'] },
    { char: '🏐', keywords: ['volleyball', 'voley', 'pelota'] },
    { char: '🏉', keywords: ['rugby', 'pelota'] },
    { char: '🎱', keywords: ['8ball', 'pool', 'billar'] },
    { char: '🏓', keywords: ['pingpong', 'tabletennis', 'paleta'] },
    { char: '🏸', keywords: ['badminton', 'paleta'] },
    { char: '🥊', keywords: ['boxing', 'glove', 'guante', 'box'] },
    { char: '🥋', keywords: ['martialarts', 'karate', 'judo'] },
    { char: '⛳', keywords: ['golf', 'flag', 'bandera'] },
    { char: '🎿', keywords: ['ski', 'snow', 'esqui', 'nieve'] },
    { char: '🏂', keywords: ['snowboard', 'snow'] },
    { char: '🏋️', keywords: ['weightlift', 'gym', 'pesas', 'gimnasio'] },
    { char: '🤸', keywords: ['cartwheel', 'gym', 'gimnasia'] },
    { char: '🏃', keywords: ['running', 'run', 'correr'] },
    { char: '🚴', keywords: ['biking', 'bike', 'cyclist', 'bici', 'ciclista'] },
    { char: '🏊', keywords: ['swim', 'swimming', 'nadar', 'natacion'] },
    { char: '🧘', keywords: ['yoga', 'meditate', 'meditacion'] },
    { char: '🎤', keywords: ['microphone', 'mic', 'sing', 'microfono', 'cantar'] },
    { char: '🎧', keywords: ['headphones', 'music', 'auriculares', 'musica'] },
    { char: '🎵', keywords: ['note', 'music', 'nota', 'musica'] },
    { char: '🎶', keywords: ['notes', 'music', 'notas', 'musica'] },
    { char: '🎸', keywords: ['guitar', 'guitarra'] },
    { char: '🥁', keywords: ['drum', 'tambor', 'bateria'] },
    { char: '🎹', keywords: ['piano', 'keyboard', 'teclado'] },
    { char: '🎬', keywords: ['clapper', 'movie', 'cine', 'pelicula'] },
    { char: '🎨', keywords: ['art', 'palette', 'arte', 'paleta'] },
    { char: '🎭', keywords: ['theater', 'masks', 'teatro', 'mascaras'] },
    { char: '🎲', keywords: ['dice', 'game', 'dado', 'juego'] },
    { char: '🧩', keywords: ['puzzle', 'pieza', 'rompecabezas'] },
    { char: '♟️', keywords: ['chess', 'pawn', 'ajedrez', 'peon'] },
];
