import type { EmojiEntry } from './types';

/** The Animals tab of the picker. */
export const ANIMALS: EmojiEntry[] = [
    { char: '🐶', keywords: ['dog', 'puppy', 'face', 'perro', 'cachorro', 'cara'] },
    { char: '🐱', keywords: ['cat', 'kitten', 'face', 'gato', 'minino', 'cara'] },
    { char: '🐭', keywords: ['mouse', 'face', 'raton', 'cara'] },
    { char: '🐹', keywords: ['hamster', 'face', 'cara'] },
    { char: '🐰', keywords: ['rabbit', 'bunny', 'face', 'conejo', 'cara'] },
    { char: '🦊', keywords: ['fox', 'face', 'zorro', 'cara'] },
    { char: '🐻', keywords: ['bear', 'face', 'oso', 'cara'] },
    { char: '🐼', keywords: ['panda', 'bear', 'face', 'oso', 'cara'] },
    { char: '🐨', keywords: ['koala', 'face', 'cara'] },
    { char: '🐯', keywords: ['tiger', 'face', 'tigre', 'cara'] },
    { char: '🦁', keywords: ['lion', 'face', 'leon', 'cara'] },
    { char: '🐮', keywords: ['cow', 'face', 'vaca', 'cara'] },
    { char: '🐷', keywords: ['pig', 'face', 'cerdo', 'chancho', 'cara'] },
    { char: '🐸', keywords: ['frog', 'face', 'rana', 'sapo', 'cara'] },
    { char: '🐵', keywords: ['monkey', 'face', 'mono', 'cara'] },
    { char: '🙈', keywords: ['seenoevil', 'monkey', 'mono', 'no', 'ver'] },
    { char: '🙉', keywords: ['hearnoevil', 'monkey', 'mono', 'no', 'oir'] },
    { char: '🙊', keywords: ['speaknoevil', 'monkey', 'mono', 'no', 'hablar'] },
    { char: '🐔', keywords: ['chicken', 'gallina', 'pollo'] },
    { char: '🐧', keywords: ['penguin', 'pinguino'] },
    { char: '🐦', keywords: ['bird', 'pajaro', 'ave'] },
    { char: '🐤', keywords: ['chick', 'baby', 'pollito', 'pollo'] },
    { char: '🦆', keywords: ['duck', 'pato'] },
    { char: '🦅', keywords: ['eagle', 'aguila'] },
    { char: '🦉', keywords: ['owl', 'buho', 'lechuza'] },
    { char: '🐺', keywords: ['wolf', 'lobo'] },
    { char: '🐗', keywords: ['boar', 'pig', 'jabali'] },
    { char: '🐴', keywords: ['horse', 'face', 'caballo', 'cara'] },
    { char: '🦄', keywords: ['unicorn', 'unicornio'] },
    { char: '🐝', keywords: ['bee', 'honeybee', 'abeja'] },
    { char: '🐛', keywords: ['bug', 'gusano', 'oruga'] },
    { char: '🦋', keywords: ['butterfly', 'mariposa'] },
    { char: '🐌', keywords: ['snail', 'caracol'] },
    { char: '🐞', keywords: ['ladybug', 'mariquita', 'vaquita', 'sanantonio'] },
    { char: '🐢', keywords: ['turtle', 'tortuga'] },
    { char: '🐍', keywords: ['snake', 'serpiente', 'vibora'] },
    { char: '🦖', keywords: ['trex', 'dinosaur', 'dinosaurio'] },
    { char: '🐙', keywords: ['octopus', 'pulpo'] },
    { char: '🦑', keywords: ['squid', 'calamar'] },
    { char: '🦀', keywords: ['crab', 'cangrejo'] },
    { char: '🐠', keywords: ['fish', 'tropical', 'pez', 'pescado'] },
    { char: '🐬', keywords: ['dolphin', 'delfin'] },
    { char: '🐳', keywords: ['whale', 'ballena'] },
    { char: '🦈', keywords: ['shark', 'tiburon'] },
];
