import type { EmojiEntry } from './types';

/** The Food tab of the picker. */
export const FOOD: EmojiEntry[] = [
    { char: '🍎', keywords: ['apple', 'red', 'fruit', 'manzana', 'roja', 'fruta'] },
    { char: '🍊', keywords: ['orange', 'fruit', 'naranja', 'fruta'] },
    { char: '🍋', keywords: ['lemon', 'fruit', 'limon', 'fruta'] },
    { char: '🍌', keywords: ['banana', 'fruit', 'platano', 'fruta'] },
    { char: '🍉', keywords: ['watermelon', 'fruit', 'sandia', 'fruta'] },
    { char: '🍇', keywords: ['grapes', 'fruit', 'uvas', 'fruta'] },
    { char: '🍓', keywords: ['strawberry', 'fruit', 'frutilla', 'fresa', 'fruta'] },
    { char: '🍑', keywords: ['peach', 'fruit', 'durazno', 'melocoton', 'fruta'] },
    { char: '🍍', keywords: ['pineapple', 'fruit', 'ananas', 'pina', 'fruta'] },
    { char: '🥥', keywords: ['coconut', 'coco'] },
    { char: '🥝', keywords: ['kiwi', 'fruit', 'fruta'] },
    { char: '🍅', keywords: ['tomato', 'tomate'] },
    { char: '🍆', keywords: ['eggplant', 'aubergine', 'berenjena'] },
    { char: '🥑', keywords: ['avocado', 'aguacate', 'palta'] },
    { char: '🥦', keywords: ['broccoli', 'brocoli'] },
    { char: '🥕', keywords: ['carrot', 'zanahoria'] },
    { char: '🌽', keywords: ['corn', 'maiz', 'choclo', 'elote'] },
    { char: '🌶️', keywords: ['pepper', 'spicy', 'hot', 'aji', 'picante', 'chile'] },
    { char: '🍞', keywords: ['bread', 'toast', 'pan', 'tostada'] },
    { char: '🧀', keywords: ['cheese', 'queso'] },
    { char: '🥚', keywords: ['egg', 'huevo'] },
    { char: '🍳', keywords: ['friedegg', 'egg', 'fried', 'cooking', 'huevo', 'frito', 'cocinar'] },
    { char: '🥓', keywords: ['bacon', 'tocino', 'panceta'] },
    { char: '🍔', keywords: ['burger', 'hamburger', 'hamburguesa'] },
    { char: '🍟', keywords: ['fries', 'chips', 'papas', 'fritas', 'patatas'] },
    { char: '🍕', keywords: ['pizza'] },
    { char: '🌮', keywords: ['taco'] },
    { char: '🌯', keywords: ['burrito'] },
    { char: '🍝', keywords: ['spaghetti', 'pasta', 'fideos', 'espagueti'] },
    { char: '🍣', keywords: ['sushi'] },
    { char: '🍰', keywords: ['cakeslice', 'cake', 'slice', 'torta', 'pastel', 'tarta'] },
    { char: '🎂', keywords: ['birthdaycake', 'birthday', 'cake', 'cumpleanos', 'torta', 'pastel'] },
    { char: '🍪', keywords: ['cookie', 'galleta', 'galletita'] },
    { char: '🍩', keywords: ['donut', 'doughnut', 'dona', 'rosquilla'] },
    { char: '🍿', keywords: ['popcorn', 'pochoclo', 'palomitas', 'cabritas'] },
    { char: '☕', keywords: ['coffee', 'hot', 'drink', 'cafe', 'bebida', 'caliente'] },
    { char: '🍵', keywords: ['tea', 'te', 'mate'] },
    { char: '🥤', keywords: ['soda', 'drink', 'cup', 'refresco', 'bebida', 'gaseosa', 'vaso'] },
    { char: '🍺', keywords: ['beer', 'cerveza', 'birra'] },
    { char: '🍷', keywords: ['wine', 'vino'] },
    { char: '🥂', keywords: ['champagne', 'clink', 'cheers', 'brindis', 'salud'] },
    { char: '🍫', keywords: ['chocolate', 'bar'] },
    { char: '🍦', keywords: ['icecream', 'soft', 'helado', 'crema'] },
    { char: '🍨', keywords: ['icecream', 'helado', 'copa'] },
    { char: '🍭', keywords: ['lollipop', 'paleta', 'chupetin'] },
    { char: '🍯', keywords: ['honey', 'miel', 'tarro'] },
    { char: '🥨', keywords: ['pretzel', 'galleta'] },
    { char: '🥐', keywords: ['croissant', 'medialuna', 'pan'] },
    { char: '🥖', keywords: ['baguette', 'bread', 'pan', 'frances'] },
    { char: '🥗', keywords: ['salad', 'ensalada', 'verde'] },
    { char: '🍜', keywords: ['ramen', 'noodles', 'sopa', 'fideos'] },
    { char: '🍲', keywords: ['pot', 'stew', 'guiso', 'olla', 'sopa'] },
    { char: '🍛', keywords: ['curry', 'rice', 'arroz'] },
    { char: '🍚', keywords: ['rice', 'arroz', 'tazon'] },
    { char: '🥟', keywords: ['dumpling', 'empanada', 'gyoza'] },
    { char: '🥪', keywords: ['sandwich', 'sanguche'] },
    { char: '🌭', keywords: ['hotdog', 'pancho'] },
    { char: '🥞', keywords: ['pancakes', 'panqueques', 'crepes'] },
    { char: '🍤', keywords: ['shrimp', 'tempura', 'camaron', 'gamba'] },
    { char: '🍙', keywords: ['onigiri', 'rice', 'ball', 'arroz'] },
    { char: '🍱', keywords: ['bento', 'box', 'almuerzo'] },
];
