import type { EmojiEntry } from './types';

/** The Gestures tab of the picker. */
export const GESTURES: EmojiEntry[] = [
    { char: '👍', keywords: ['thumbsup', 'thumbs', 'up', 'yes', 'ok', 'like', 'pulgar', 'arriba', 'bien', 'si', 'aprobado', 'dale'] },
    { char: '👎', keywords: ['thumbsdown', 'thumbs', 'down', 'no', 'dislike', 'pulgar', 'abajo', 'mal', 'rechazo'] },
    { char: '👌', keywords: ['ok', 'hand', 'perfect', 'mano', 'perfecto', 'genial'] },
    { char: '🤌', keywords: ['pinched', 'fingers', 'italian', 'dedos', 'italiano', 'pellizco'] },
    { char: '🤏', keywords: ['pinch', 'small', 'pellizco', 'pequeno', 'poquito'] },
    { char: '✌️', keywords: ['peace', 'victory', 'paz', 'victoria', 'dos'] },
    { char: '🤞', keywords: ['crossed', 'fingers', 'luck', 'cruzados', 'dedos', 'suerte'] },
    { char: '🤟', keywords: ['loveyou', 'love', 'you', 'rock', 'te', 'amo', 'amor', 'senas'] },
    { char: '🤘', keywords: ['rock', 'horns', 'metal', 'cuernos'] },
    { char: '🤙', keywords: ['call', 'me', 'shaka', 'llamame', 'llamar'] },
    { char: '👈', keywords: ['pointleft', 'point', 'left', 'senalar', 'izquierda', 'dedo'] },
    { char: '👉', keywords: ['pointright', 'point', 'right', 'senalar', 'derecha', 'dedo'] },
    { char: '👆', keywords: ['pointup', 'point', 'up', 'senalar', 'arriba', 'dedo'] },
    { char: '👇', keywords: ['pointdown', 'point', 'down', 'senalar', 'abajo', 'dedo'] },
    { char: '☝️', keywords: ['index', 'up', 'one', 'indice', 'arriba', 'uno'] },
    { char: '👋', keywords: ['wave', 'hi', 'hello', 'bye', 'hola', 'adios', 'saludar', 'chau'] },
    { char: '🖐️', keywords: ['hand', 'splayed', 'five', 'mano', 'abierta', 'cinco'] },
    { char: '✋', keywords: ['raised', 'hand', 'stop', 'high', 'five', 'mano', 'alta', 'pare', 'alto'] },
    { char: '🖖', keywords: ['vulcan', 'spock', 'vulcano', 'startrek'] },
    { char: '👏', keywords: ['clap', 'applause', 'aplauso', 'aplaudir', 'palmas'] },
    { char: '🙌', keywords: ['raised', 'hands', 'celebrate', 'praise', 'manos', 'celebrar', 'alabar'] },
    { char: '👐', keywords: ['openhands', 'open', 'hands', 'manos', 'abiertas'] },
    { char: '🤲', keywords: ['palms', 'up', 'palmas', 'rezar'] },
    { char: '🤝', keywords: ['handshake', 'deal', 'apreton', 'trato', 'acuerdo'] },
    { char: '🙏', keywords: ['pray', 'please', 'thanks', 'rezar', 'rogar', 'porfavor', 'gracias'] },
    { char: '💪', keywords: ['muscle', 'flex', 'strong', 'musculo', 'fuerza', 'fuerte', 'biceps'] },
    { char: '🫶', keywords: ['hearthands', 'heart', 'hands', 'love', 'corazon', 'manos', 'amor'] },
    { char: '❤️', keywords: ['heart', 'love', 'red', 'corazon', 'amor', 'rojo'] },
    { char: '🧡', keywords: ['orangeheart', 'heart', 'orange', 'corazon', 'naranja'] },
    { char: '💛', keywords: ['yellowheart', 'heart', 'yellow', 'corazon', 'amarillo'] },
    { char: '💚', keywords: ['greenheart', 'heart', 'green', 'corazon', 'verde'] },
    { char: '💙', keywords: ['blueheart', 'heart', 'blue', 'corazon', 'azul'] },
    { char: '💜', keywords: ['purpleheart', 'heart', 'purple', 'corazon', 'morado', 'violeta'] },
    { char: '🖤', keywords: ['blackheart', 'heart', 'black', 'corazon', 'negro'] },
    { char: '🤍', keywords: ['whiteheart', 'heart', 'white', 'corazon', 'blanco'] },
    { char: '🤎', keywords: ['brownheart', 'heart', 'brown', 'corazon', 'marron', 'cafe'] },
    { char: '💔', keywords: ['brokenheart', 'broken', 'heart', 'corazon', 'roto', 'partido'] },
    { char: '💕', keywords: ['twohearts', 'hearts', 'love', 'corazones', 'amor'] },
    { char: '💖', keywords: ['sparklingheart', 'sparkling', 'heart', 'love', 'corazon', 'brillante', 'amor'] },
];
