import type { EmojiEntry } from './types';

/** The Objects tab of the picker. */
export const OBJECTS: EmojiEntry[] = [
    { char: '🔥', keywords: ['fire', 'lit', 'hot', 'fuego', 'llama', 'caliente', 'genial'] },
    { char: '✨', keywords: ['sparkles', 'shine', 'brillos', 'destellos', 'magia'] },
    { char: '⭐', keywords: ['star', 'estrella'] },
    { char: '🌟', keywords: ['glowingstar', 'glowing', 'star', 'estrella', 'brillante'] },
    { char: '💫', keywords: ['dizzy', 'star', 'mareo', 'estrella'] },
    { char: '⚡', keywords: ['zap', 'lightning', 'bolt', 'rayo', 'relampago', 'electricidad'] },
    { char: '☀️', keywords: ['sun', 'sunny', 'sol', 'soleado'] },
    { char: '🌙', keywords: ['moon', 'night', 'luna', 'noche'] },
    { char: '☁️', keywords: ['cloud', 'weather', 'nube', 'clima'] },
    { char: '🌈', keywords: ['rainbow', 'pride', 'arcoiris', 'orgullo'] },
    { char: '💧', keywords: ['droplet', 'water', 'gota', 'agua'] },
    { char: '🎉', keywords: ['tada', 'party', 'celebrate', 'fiesta', 'celebrar', 'cumpleanos'] },
    { char: '🎊', keywords: ['confetti', 'celebrate', 'confeti', 'celebrar', 'fiesta'] },
    { char: '🎁', keywords: ['gift', 'present', 'regalo', 'presente'] },
    { char: '🏆', keywords: ['trophy', 'win', 'trofeo', 'ganar', 'victoria', 'copa'] },
    { char: '🥇', keywords: ['goldmedal', 'gold', 'medal', 'first', 'oro', 'medalla', 'primero'] },
    { char: '🎯', keywords: ['target', 'bullseye', 'dart', 'diana', 'objetivo', 'tiro'] },
    { char: '🎮', keywords: ['videogame', 'video', 'game', 'gaming', 'videojuego', 'juego', 'control', 'gamer'] },
    { char: '📱', keywords: ['phone', 'mobile', 'telefono', 'celular', 'movil'] },
    { char: '💻', keywords: ['laptop', 'computer', 'computadora', 'portatil', 'notebook', 'pc', 'ordenador'] },
    { char: '⌨️', keywords: ['keyboard', 'teclado'] },
    { char: '🖱️', keywords: ['mouse', 'computer', 'raton', 'computadora'] },
    { char: '💾', keywords: ['floppy', 'disk', 'save', 'disquete', 'guardar'] },
    { char: '📷', keywords: ['camera', 'photo', 'camara', 'foto'] },
    { char: '🎥', keywords: ['movie', 'camera', 'film', 'pelicula', 'cine'] },
    { char: '💡', keywords: ['bulb', 'idea', 'lightbulb', 'bombilla', 'foco', 'bombita'] },
    { char: '📚', keywords: ['books', 'read', 'libros', 'leer', 'estudio'] },
    { char: '📖', keywords: ['book', 'open', 'read', 'libro', 'abierto', 'leer'] },
    { char: '📝', keywords: ['memo', 'note', 'write', 'nota', 'escribir', 'apunte'] },
    { char: '✏️', keywords: ['pencil', 'write', 'lapiz', 'escribir'] },
    { char: '📌', keywords: ['pushpin', 'pin', 'chincheta', 'alfiler', 'fijar'] },
    { char: '🔗', keywords: ['link', 'chain', 'enlace', 'cadena'] },
    { char: '🔒', keywords: ['lock', 'locked', 'candado', 'cerrado', 'bloqueado'] },
    { char: '🔑', keywords: ['key', 'llave', 'clave'] },
    { char: '🛠️', keywords: ['tools', 'hammer', 'wrench', 'herramientas', 'martillo'] },
    { char: '⚙️', keywords: ['gear', 'settings', 'engranaje', 'ajustes', 'configuracion'] },
];
