import type { EmojiEntry } from './types';

/** The Smileys tab of the picker. */
export const SMILEYS: EmojiEntry[] = [
    { char: '😀', keywords: ['grinning', 'smile', 'happy', 'face', 'sonrisa', 'feliz', 'cara', 'contento'] },
    { char: '😃', keywords: ['smile', 'happy', 'joy', 'face', 'sonrisa', 'feliz', 'alegre', 'cara'] },
    { char: '😄', keywords: ['smile', 'happy', 'laugh', 'face', 'sonrisa', 'risa', 'feliz', 'cara'] },
    { char: '😁', keywords: ['beaming', 'smile', 'grin', 'sonrisa', 'dientes', 'feliz'] },
    { char: '😆', keywords: ['laugh', 'haha', 'xd', 'risa', 'carcajada'] },
    { char: '😅', keywords: ['sweat', 'laugh', 'relief', 'sudor', 'alivio', 'risa'] },
    { char: '🤣', keywords: ['rofl', 'laugh', 'rolling', 'risa', 'revolcando', 'carcajada'] },
    { char: '😂', keywords: ['joy', 'tears', 'laugh', 'lol', 'risa', 'lagrimas', 'llorar'] },
    { char: '🙂', keywords: ['slight', 'smile', 'face', 'leve', 'sonrisa', 'cara'] },
    { char: '🙃', keywords: ['upside', 'down', 'face', 'reves', 'cabeza', 'abajo', 'cara'] },
    { char: '😉', keywords: ['wink', 'face', 'guino', 'ojo', 'cara'] },
    { char: '😊', keywords: ['blush', 'smile', 'happy', 'rubor', 'sonrojar', 'feliz', 'sonrisa'] },
    { char: '😇', keywords: ['halo', 'angel', 'innocent', 'aureola', 'inocente', 'santo'] },
    { char: '🥰', keywords: ['love', 'hearts', 'smile', 'amor', 'enamorado', 'corazones'] },
    { char: '😍', keywords: ['heart', 'eyes', 'love', 'corazon', 'ojos', 'enamorado', 'amor'] },
    { char: '🤩', keywords: ['star', 'struck', 'wow', 'estrella', 'asombrado', 'impresionado'] },
    { char: '😘', keywords: ['kiss', 'love', 'face', 'beso', 'amor', 'cara'] },
    { char: '😋', keywords: ['yum', 'tongue', 'tasty', 'lengua', 'rico', 'delicioso', 'sabroso'] },
    { char: '😛', keywords: ['tongue', 'face', 'lengua', 'cara'] },
    { char: '😜', keywords: ['wink', 'tongue', 'silly', 'guino', 'lengua', 'tonto'] },
    { char: '🤪', keywords: ['zany', 'crazy', 'silly', 'loco', 'tonto', 'chiflado'] },
    { char: '🤗', keywords: ['hug', 'face', 'abrazo', 'cara'] },
    { char: '🤔', keywords: ['thinking', 'hmm', 'face', 'pensando', 'pensar', 'duda'] },
    { char: '🤨', keywords: ['raised', 'eyebrow', 'suspicious', 'ceja', 'levantada', 'sospecha', 'duda'] },
    { char: '😐', keywords: ['neutral', 'meh', 'face', 'neutral', 'cara', 'serio'] },
    { char: '😑', keywords: ['expressionless', 'face', 'sin', 'expresion', 'cara'] },
    { char: '😶', keywords: ['silent', 'no', 'mouth', 'silencio', 'boca', 'callado'] },
    { char: '😏', keywords: ['smirk', 'face', 'sonrisa', 'picara', 'burla'] },
    { char: '😒', keywords: ['unamused', 'meh', 'aburrido', 'disgusto'] },
    { char: '🙄', keywords: ['eye', 'roll', 'rolling', 'ojos', 'rodar', 'fastidio'] },
    { char: '😬', keywords: ['grimace', 'awkward', 'mueca', 'incomodo', 'tension'] },
    { char: '😌', keywords: ['relieved', 'calm', 'aliviado', 'calmado', 'tranquilo'] },
    { char: '😔', keywords: ['pensive', 'sad', 'pensativo', 'triste'] },
    { char: '😪', keywords: ['sleepy', 'tired', 'sueno', 'cansado', 'dormir'] },
    { char: '😴', keywords: ['sleep', 'zzz', 'dormir', 'dormido', 'sueno'] },
    { char: '😷', keywords: ['mask', 'sick', 'mascara', 'barbijo', 'enfermo', 'cubrebocas'] },
    { char: '🤒', keywords: ['sick', 'thermometer', 'ill', 'enfermo', 'termometro', 'fiebre'] },
    { char: '🤕', keywords: ['hurt', 'bandage', 'injured', 'herido', 'venda', 'lastimado'] },
    { char: '🥳', keywords: ['party', 'celebrate', 'hat', 'fiesta', 'celebrar', 'gorro', 'cumpleanos'] },
    { char: '😎', keywords: ['cool', 'sunglasses', 'lentes', 'gafas', 'sol', 'chevere', 'genial'] },
    { char: '🤓', keywords: ['nerd', 'glasses', 'geek', 'nerd', 'lentes', 'gafas', 'empollon'] },
    { char: '🧐', keywords: ['monocle', 'inspect', 'monoculo', 'inspeccionar', 'detective'] },
    { char: '😕', keywords: ['confused', 'face', 'confundido', 'cara'] },
    { char: '🙁', keywords: ['frown', 'sad', 'triste', 'cara'] },
    { char: '😮', keywords: ['open', 'mouth', 'wow', 'boca', 'abierta', 'asombro'] },
    { char: '😲', keywords: ['astonished', 'shock', 'asombrado', 'sorprendido', 'shock'] },
    { char: '😳', keywords: ['flushed', 'blush', 'sonrojado', 'verguenza', 'rubor'] },
    { char: '🥺', keywords: ['pleading', 'puppy', 'eyes', 'suplicando', 'cachorro', 'ojos'] },
    { char: '😢', keywords: ['cry', 'sad', 'tear', 'llorar', 'triste', 'lagrima'] },
    { char: '😭', keywords: ['sob', 'cry', 'bawl', 'sollozar', 'llorar', 'llanto'] },
    { char: '😱', keywords: ['scream', 'shock', 'fear', 'grito', 'miedo', 'asustado'] },
    { char: '😨', keywords: ['fearful', 'scared', 'miedo', 'asustado'] },
    { char: '😰', keywords: ['anxious', 'sweat', 'ansioso', 'sudor', 'nervioso'] },
    { char: '😡', keywords: ['angry', 'mad', 'rage', 'enojado', 'enfadado', 'furioso', 'rabia'] },
    { char: '😠', keywords: ['angry', 'mad', 'enojado', 'enfadado'] },
];
